name: Linux Releases

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_TYPE: Release

jobs:
  linux_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: Create Build Directory
      run: cmake -E make_directory ./build/

    - name: Configure CMake
      shell: bash
      working-directory: ./build/
      run: cmake ../

    - name: Build Project
      working-directory: ./build/
      shell: bash
      run: cmake --build . --target hello
