name: Mac Releases

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_TYPE: Release
  FC: /usr/local/bin/gfortran-9
  MACOSX_DEPLOYMENT_TARGET: 10.15
  SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

jobs:
  mac_release:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall
